Repository googleapis/java-security-private-ca, pull requests merged in 2020-09, with the labels that each got.

#9 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#11 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#12 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#23 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#22 chore: add repo settings configuration
  .github/readme/synth.py
  .github/sync-repo-settings.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  .repo-metadata.json
  synth.metadata
Labels: automerge, cla: yes

#30 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#32 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
